application: broken-links-analyzer
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: lxml
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'
- url: /static
  static_dir: static

env_variables:
    DJANGO_SETTINGS_MODULE: 'broken_links_analyzer.settings'
